server:
  port: 8010
spring:
  application:
    name: eureka-server-tutorial
eureka:
  instance:
    lease-expiration-duration-in-seconds: 3
  server:
    enable-self-preservation: false
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8010/eureka/
    healthcheck:
      enabled: true
