spring:
  application:
    name: config_server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cengizhanozcan/microservice-spring-cloud-eureka
          search-paths: config_data

server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/
